// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static FirebaseOptions web = _webOptions();

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD129QHoR_so88afjMLAq4No4TX3b2dqec',
    appId: '1:1098759282020:android:9af5126bc9d538adfaae71',
    messagingSenderId: '1098759282020',
    projectId: 'tictacfour-c6cc5',
    storageBucket: 'tictacfour-c6cc5.firebasestorage.app',
  );

  static FirebaseOptions windows = _windowsOptions();

  static FirebaseOptions _webOptions() {
    const apiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
    if (apiKey.isEmpty) {
      throw StateError('Missing FIREBASE_WEB_API_KEY; supply via --dart-define.');
    }

    return const FirebaseOptions(
      apiKey: apiKey,
      appId: '1:1098759282020:web:19460668da4e17d5faae71',
      messagingSenderId: '1098759282020',
      projectId: 'tictacfour-c6cc5',
      authDomain: 'tictacfour-c6cc5.firebaseapp.com',
      storageBucket: 'tictacfour-c6cc5.firebasestorage.app',
    );
  }

  static FirebaseOptions _windowsOptions() {
    const apiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
    if (apiKey.isEmpty) {
      throw StateError('Missing FIREBASE_WEB_API_KEY; supply via --dart-define.');
    }

    return const FirebaseOptions(
      apiKey: apiKey,
      appId: '1:1098759282020:web:78efb4fbfff5ce39faae71',
      messagingSenderId: '1098759282020',
      projectId: 'tictacfour-c6cc5',
      authDomain: 'tictacfour-c6cc5.firebaseapp.com',
      storageBucket: 'tictacfour-c6cc5.firebasestorage.app',
    );
  }
}
